package bossq

const storeTemplate = `// Code generated by BossQ; DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"fmt"
	"time"
	"strings" 
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"
)

// {{.StoreName}} — потокобезопасный store для работы с таблицей {{.TableName}}.
type {{.StoreName}} struct {
	pool *pgxpool.Pool
}

// New{{.StoreName}} создаёт новый store.
func New{{.StoreName}}(pool *pgxpool.Pool) *{{.StoreName}} {
	return &{{.StoreName}}{pool: pool}
}
{{range .Methods}}
{{.}}
{{end}}
`

const createMethod = `
// Create вставляет новую запись и возвращает её с автосгенерированными полями.
func (s *{{.StoreName}}) Create(ctx context.Context, m *{{.ModelName}}) (*{{.ModelName}}, error) {
	row := s.pool.QueryRow(ctx,
		` + "`INSERT INTO {{.TableName}} ({{.InsertColumns}}) VALUES ({{.InsertPlaceholders}}) RETURNING {{.ReturningColumns}}`" + `,
		{{.InsertValues}},
	)
	var newM {{.ModelName}}
	err := row.Scan({{.ScanReturning}})
	if err != nil {
		return nil, fmt.Errorf("create {{.TableName}}: %w", err)
	}
	{{.CopyBackFields}}
	return &newM, nil
}
`

const getByIDMethod = `
// GetByID находит запись по первичному ключу.
func (s *{{.StoreName}}) GetByID(ctx context.Context, id int64) (*{{.ModelName}}, error) {
	m := &{{.ModelName}}{}
	err := s.pool.QueryRow(ctx,
		` + "`SELECT {{.AllColumns}} FROM {{.TableName}} WHERE {{.PKColumn}} = $1`" + `,
		id,
	).Scan({{.ScanAll}})
	if err != nil {
		return nil, fmt.Errorf("get {{.TableName}} %d: %w", id, err)
	}
	return m, nil
}
`

const updateMethod = `
// Update обновляет все поля записи.
func (s *{{.StoreName}}) Update(ctx context.Context, m *{{.ModelName}}) error {
	tag, err := s.pool.Exec(ctx,
		` + "`UPDATE {{.TableName}} SET {{.SetClauses}} WHERE {{.PKColumn}} = ${{.PKIndex}}`" + `,
		{{.UpdateValues}},
	)
	if err != nil {
		return fmt.Errorf("update {{.TableName}} %d: %w", m.{{.PKField}}, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("{{.TableName}} %d not found", m.{{.PKField}})
	}
	return nil
}
`

const deleteMethod = `
// Delete удаляет запись по ID.
func (s *{{.StoreName}}) Delete(ctx context.Context, id int64) error {
	_, err := s.pool.Exec(ctx,
		` + "`DELETE FROM {{.TableName}} WHERE {{.PKColumn}} = $1`" + `,
		id,
	)
	return err
}
`

const listMethod = `
// List возвращает все записи с пагинацией.
func (s *{{.StoreName}}) List(ctx context.Context, limit, offset int) ([]{{.ModelName}}, error) {
	rows, err := s.pool.Query(ctx,
		` + "`SELECT {{.AllColumns}} FROM {{.TableName}} ORDER BY {{.PKColumn}} DESC LIMIT $1 OFFSET $2`" + `,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("list {{.TableName}}: %w", err)
	}
	defer rows.Close()

	var items []{{.ModelName}}
	for rows.Next() {
		var m {{.ModelName}}
		if err := rows.Scan({{.ScanAll}}); err != nil {
			return nil, fmt.Errorf("scan {{.TableName}}: %w", err)
		}
		items = append(items, m)
	}
	return items, rows.Err()
}
`

const bulkInsertMethod = `
// BulkInsert использует pgx.CopyFrom для сверхбыстрой вставки множества записей.
func (s *{{.StoreName}}) BulkInsert(ctx context.Context, items []{{.ModelName}}) (int64, error) {
	return s.pool.CopyFrom(
		ctx,
		pgx.Identifier{"{{.TableName}}"},
		[]string{ {{.ColumnNamesForCopy}} },
		pgx.CopyFromSlice(len(items), func(i int) ([]interface{}, error) {
			m := items[i]
			return []interface{}{ {{.CopyValues}} }, nil
		}),
	)
}
`

const queryBuilderTemplate = `
// {{.ModelName}}QueryBuilder — типобезопасный построитель запросов для таблицы {{.TableName}}.
type {{.ModelName}}QueryBuilder struct {
	pool    *pgxpool.Pool
	where   []string
	args    []interface{}
	orderBy string
	limit   int
	offset  int
}

// New{{.ModelName}}QueryBuilder создаёт новый построитель запросов.
func New{{.ModelName}}QueryBuilder(pool *pgxpool.Pool) *{{.ModelName}}QueryBuilder {
	return &{{.ModelName}}QueryBuilder{pool: pool}
}
{{range .FieldMethods}}
{{.}}
{{end}}
// OrderBy задаёт сортировку (например, "id DESC").
func (qb *{{.ModelName}}QueryBuilder) OrderBy(order string) *{{.ModelName}}QueryBuilder {
	qb.orderBy = order
	return qb
}

// Limit устанавливает максимальное количество возвращаемых строк.
func (qb *{{.ModelName}}QueryBuilder) Limit(limit int) *{{.ModelName}}QueryBuilder {
	qb.limit = limit
	return qb
}

// Offset задаёт смещение для пагинации.
func (qb *{{.ModelName}}QueryBuilder) Offset(offset int) *{{.ModelName}}QueryBuilder {
	qb.offset = offset
	return qb
}

// All выполняет запрос и возвращает все подходящие записи.
func (qb *{{.ModelName}}QueryBuilder) All(ctx context.Context) ([]{{.ModelName}}, error) {
	query := "SELECT * FROM {{.TableName}}"
	if len(qb.where) > 0 {
		query += " WHERE " + qb.whereClause()
	}
	if qb.orderBy != "" {
		query += " ORDER BY " + qb.orderBy
	}
	if qb.limit > 0 {
		query += fmt.Sprintf(" LIMIT %d", qb.limit)
	}
	if qb.offset > 0 {
		query += fmt.Sprintf(" OFFSET %d", qb.offset)
	}
	rows, err := qb.pool.Query(ctx, query, qb.args...)
	if err != nil {
		return nil, fmt.Errorf("query {{.TableName}}: %w", err)
	}
	defer rows.Close()

	var items []{{.ModelName}}
	for rows.Next() {
		var m {{.ModelName}}
		if err := rows.Scan({{.ScanAll}}); err != nil {
			return nil, fmt.Errorf("scan {{.TableName}}: %w", err)
		}
		items = append(items, m)
	}
	return items, rows.Err()
}

// First возвращает первую запись, удовлетворяющую условиям.
func (qb *{{.ModelName}}QueryBuilder) First(ctx context.Context) (*{{.ModelName}}, error) {
	qb.limit = 1
	items, err := qb.All(ctx)
	if err != nil {
		return nil, err
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("{{.TableName}}: no rows found")
	}
	return &items[0], nil
}

// Count возвращает количество записей, удовлетворяющих условиям.
func (qb *{{.ModelName}}QueryBuilder) Count(ctx context.Context) (int, error) {
	query := "SELECT COUNT(*) FROM {{.TableName}}"
	if len(qb.where) > 0 {
		query += " WHERE " + qb.whereClause()
	}
	var count int
	err := qb.pool.QueryRow(ctx, query, qb.args...).Scan(&count)
	return count, err
}

// whereClause собирает все условия в одну строку.
func (qb *{{.ModelName}}QueryBuilder) whereClause() string {
	// Простое объединение через AND; в реальном коде нужно учитывать OR/AND-группы.
	return strings.Join(qb.where, " AND ")
}
`

const fieldWhereMethod = `
// Where{{.FieldName}} добавляет условие для колонки "{{.ColumnName}}".
func (qb *{{.ModelName}}QueryBuilder) Where{{.FieldName}}(op string, val {{.FieldType}}) *{{.ModelName}}QueryBuilder {
	qb.where = append(qb.where, fmt.Sprintf("{{.ColumnName}} %s $%d", op, len(qb.args)+1))
	qb.args = append(qb.args, val)
	return qb
}

// AndWhere{{.FieldName}} добавляет условие с AND для колонки "{{.ColumnName}}".
func (qb *{{.ModelName}}QueryBuilder) AndWhere{{.FieldName}}(op string, val {{.FieldType}}) *{{.ModelName}}QueryBuilder {
	qb.where = append(qb.where, fmt.Sprintf("AND {{.ColumnName}} %s $%d", op, len(qb.args)+1))
	qb.args = append(qb.args, val)
	return qb
}
`

const loadHasManyTemplate = `
// Load{{.RelationName}} загружает все {{.RelationName}} для данной модели.
func (s *{{.StoreName}}) Load{{.RelationName}}(ctx context.Context, m *{{.ModelName}}) error {
    rows, err := s.pool.Query(ctx,
        ` + "`SELECT * FROM {{.TargetTable}} WHERE {{.ForeignKey}} = $1`" + `,
        m.{{.PKField}},
    )
    if err != nil {
        return fmt.Errorf("load {{.RelationName}} for {{.ModelName}}: %w", err)
    }
    defer rows.Close()

    m.{{.RelationName}} = make({{.FieldType}}, 0)
    for rows.Next() {
        var item {{.TargetModel}}
        if err := rows.Scan({{.ScanFields}}); err != nil {
            return err
        }
        m.{{.RelationName}} = append(m.{{.RelationName}}, item)
    }
    return rows.Err()
}
`

const loadBelongsToTemplate = `
// Load{{.RelationName}} загружает связанный {{.RelationName}} для модели.
func (s *{{.StoreName}}) Load{{.RelationName}}(ctx context.Context, m *{{.ModelName}}) error {
    if m.{{.FKField}} == 0 {
        return nil // или ошибка, зависит от логики
    }
    var item {{.TargetModel}}
    err := s.pool.QueryRow(ctx,
        ` + "`SELECT * FROM {{.TargetTable}} WHERE {{.TargetPK}} = $1`" + `,
        m.{{.FKField}},
    ).Scan({{.ScanFields}})
    if err != nil {
        return fmt.Errorf("load {{.RelationName}} for {{.ModelName}}: %w", err)
    }
    m.{{.RelationName}} = &item
    return nil
}
`

// Выполнено с любовью для Босса 🐈‍